trigger:
  branches:
    include:
      - main

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Java-App-1
      trigger: true

stages:
  - stage: Dev
    jobs:
      - job: DeployToDev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'Java-App-1'
              pipeline: '$(buildPipeline)'
              buildVersionToDownload: 'latest'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'ForzaAzureRMConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
                az account set --subscription $(subscriptionId)
                terraform init
                terraform apply -auto-approve -var 'subscription_id=$(subscriptionId)' -var 'client_id=$(servicePrincipalId)' -var 'client_secret=$(servicePrincipalKey)' -var 'tenant_id=$(tenantId)'
            workingDirectory: Infra-Folder
            displayName: 'Provision Infrastructure'
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
              namespace: 'dev'
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'yaml'
              configuration: '$(System.ArtifactsDirectory)/drop/k8s/deployment.yaml'
            displayName: 'Deploy to Kubernetes'

  - stage: Prod
    jobs:
      - job: DeployToProd
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'Java-App-1'
              pipeline: '$(buildPipeline)'
              buildVersionToDownload: 'latest'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'ForzaAzureRMConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
                az account set --subscription $(subscriptionId)
                terraform init
                terraform apply -auto-approve -var 'subscription_id=$(subscriptionId)' -var 'client_id=$(servicePrincipalId)' -var 'client_secret=$(servicePrincipalKey)' -var 'tenant_id=$(tenantId)'
            workingDirectory: Infra-Folder
            displayName: 'Provision Infrastructure'
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
              namespace: 'prod'
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'yaml'
              configuration: '$(System.ArtifactsDirectory)/drop/k8s/deployment.yaml'
            displayName: 'Deploy to Kubernetes'
