trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- script: |
    echo "Cleaning workspace..."
    git clean -fdx
  displayName: 'Clean Workspace'

- script: |
    echo "Listing source directory contents"
    ls -la $(Build.SourcesDirectory)
  displayName: 'List source directory contents'

- script: |
    echo "Printing git log"
    git log -n 5
  displayName: 'Print git log'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -Dmaven.test.skip=true'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/target/spring-boot-docker-complete-0.0.1-SNAPSHOT.jar'
    artifactName: 'forza-java-webapp'
    publishLocation: 'pipeline'

- task: Docker@2
  inputs:
    containerRegistry: 'ForzaDockerRegistryConnection'
    repository: 'stforza/java-webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
    arguments: '--no-cache'
