trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Options: 'macOS-latest', 'windows-latest'

variables:
- group: 'Tomcat Login Info'  # Reference the variable group

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Adjust path if your pom.xml is in a subdirectory
    mavenOptions: '-Xmx3072m'  # JVM options
    javaHomeOption: 'JDKVersion'  # Use JDK version installed on the agent
    jdkVersionOption: '1.8'  # JDK version 1.8
    jdkArchitectureOption: 'x64'  # JDK architecture
    publishJUnitResults: true  # Publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Test results pattern
    goals: 'package'  # Maven goals to execute

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/target/*.war'  # Path to your WAR file
    artifactName: 'forza-java-webapp'  # Name of the artifact to publish

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'forza-java-webapp'
    targetPath: '$(System.ArtifactsDirectory)/webapp'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/webapp'
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      WAR_FILE=$(find $(Build.ArtifactStagingDirectory) -name "*.war")
      echo "Deploying $WAR_FILE to Tomcat..."
      curl -u $(TomcatUsername):$(TomcatPassword) \
        -T "$WAR_FILE" \
        "http://your-tomcat-server:8080/manager/text/deploy?path=/your-app-context&update=true"

