trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJava@1
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    jdkVersionOption: '11'
    checkLatest: true

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'forzastorageaccount1.azurecr.io/java-webapp'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'ForzaDockerRegistryConnection'
    tags: |
      $(Build.BuildId)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ForzaAzureRMConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch -d artifacts -s $(Build.ArtifactStagingDirectory) --account-name forzastorageaccount1 --auth-mode login
