trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToDev
  steps:
    - task: UseJava@1
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        jdkVersionOption: '11'
        checkLatest: true

    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: 'your-docker-repository/java-webapp'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'ForzaDockerRegistryConnection'
        tags: |
          $(Build.BuildId)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

- job: DeployToProd
  environment: 'Production'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
          - task: UseJava@1
            inputs:
              versionSpec: '11'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
              jdkVersionOption: '11'
              checkLatest: true

          - task: Docker@2
            inputs:
              command: 'buildAndPush'
              repository: 'your-docker-repository/java-webapp'
              dockerfile: '**/Dockerfile'
              containerRegistry: 'ForzaDockerRegistryConnection'
              tags: |
                $(Build.BuildId)

          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
              namespace: 'prod'
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'yaml'
              configuration: '$(System.DefaultWorkingDirectory)/Infra-Folder/deployment.yaml'
