trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ForzaAzureRMConnection'  # Use the AzureRM connection for the container registry
    repository: 'my-java-app'
    command: 'buildAndPush'
    Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: Kubernetes@1
  inputs:
    azureSubscriptionEndpoint: 'ForzaAzureRMConnection'  # Use the AzureRM connection for Kubernetes cluster
    resourceGroupName: 'Forza-Resource-Group-10'
    kubernetesCluster: 'ForzaAKSCluster'
    namespace: 'default'
    command: 'apply'
    useClusterAdmin: false
    arguments: '-f $(System.DefaultWorkingDirectory)/kubernetes-manifests/'
