trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
    - task: UseJava@1
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        jdkVersionOption: '11'
        checkLatest: true

    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: 'forza-dc/java-webapp'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'ForzaDockerRegistryConnection'
        tags: |
          $(Build.BuildId)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'
