trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Dev
    jobs:
      - job: DeployToDev
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'ForzaAzureRMConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage blob download-batch -d $(Pipeline.Workspace) -s artifacts --account-name forzastorageaccount1 --auth-mode login
          - script: |
              terraform init
              terraform apply -auto-approve
            workingDirectory: Infra-Folder
            displayName: 'Provision Infrastructure'
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
              namespace: 'dev'
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'yaml'
              configuration: '$(Pipeline.Workspace)/k8s/deployment.yaml'
            displayName: 'Deploy to Kubernetes'

  - stage: Prod
    jobs:
      - deployment: DeployToProd
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'ForzaAzureRMConnection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az storage blob download-batch -d $(Pipeline.Workspace) -s artifacts --account-name forzastorageaccount1 --auth-mode login
                - script: |
                    terraform init
                    terraform apply -auto-approve
                  workingDirectory: Infra-Folder
                  displayName: 'Provision Infrastructure'
                - task: Kubernetes@1
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
                    namespace: 'prod'
                    command: 'apply'
                    useConfigurationFile: true
                    configurationType: 'yaml'
                    configuration: '$(Pipeline.Workspace)/k8s/deployment.yaml'
                  displayName: 'Deploy to Kubernetes'
