trigger:
  branches:
    include:
      - main

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Java-App-1
      trigger: true

stages:
  - stage: Dev
    jobs:
      - job: DeployToDev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'Java-App-1'
              pipeline: 'Java-App-1'
              runVersion: 'latest'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)/drop'
          - script: |
              curl -LO "https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip"
              unzip terraform_1.0.3_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
            displayName: 'Install Terraform'
          - script: |
              terraform init
              terraform apply -auto-approve
            workingDirectory: Infra-Folder
            displayName: 'Provision Infrastructure'
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
              namespace: 'dev'
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'yaml'
              configuration: '$(Pipeline.Workspace)/drop/k8s/deployment.yaml'
            displayName: 'Deploy to Kubernetes'

  - stage: Prod
    jobs:
      - job: DeployToProd
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'Java-App-1'
              pipeline: 'Java-App-1'
              runVersion: 'latest'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)/drop'
          - script: |
              curl -LO "https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip"
              unzip terraform_1.0.3_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
            displayName: 'Install Terraform'
          - script: |
              terraform init
              terraform apply -auto-approve
            workingDirectory: Infra-Folder
            displayName: 'Provision Infrastructure'
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
              namespace: 'prod'
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'yaml'
              configuration: '$(Pipeline.Workspace)/drop/k8s/deployment.yaml'
            displayName: 'Deploy to Kubernetes'
