trigger:
  branches:
    include:
      - main

stages:
  - stage: Dev
    jobs:
      - job: DeployToDev
        steps:
          - script: |
              terraform init
              terraform apply -auto-approve
            workingDirectory: Infra-Folder
            displayName: 'Provision Infrastructure'
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
              namespace: 'dev'
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'yaml'
              configuration: '$(System.DefaultWorkingDirectory)/k8s/deployment.yaml'
            displayName: 'Deploy to Kubernetes'

  - stage: Prod
    jobs:
      - deployment: DeployToProd
        environment: 'Production'
        strategy:
          runOnce:
            preDeployApprovals:
              - approvers:
                  - stsamdc@hotmail.com
            deploy:
              steps:
                - script: |
                    terraform init
                    terraform apply -auto-approve
                  workingDirectory: Infra-Folder
                  displayName: 'Provision Infrastructure'
                - task: Kubernetes@1
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscriptionEndpoint: 'ForzaAzureRMConnection'
                    namespace: 'prod'
                    command: 'apply'
                    useConfigurationFile: true
                    configurationType: 'yaml'
                    configuration: '$(System.DefaultWorkingDirectory)/k8s/deployment.yaml'
                  displayName: 'Deploy to Kubernetes'
