trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: UseJava@1
#   inputs:
#     versionSpec: '11'
#     jdkArchitectureOption: 'x64'
#     jdkSourceOption: 'PreInstalled'
#     jdkVersionOption: '11'
#     checkLatest: true

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    chmod +x gradlew
    ./gradlew build
  displayName: 'Build with Gradle'

- task: Docker@2
  inputs:
    containerRegistry: 'ForzaDockerRegistryConnection'
    repository: 'forza-dc/java-webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
