trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
      jdkPathOption: '$(JAVA_HOME)'
  - script: |
      ./gradlew build
    displayName: 'Build with Gradle'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/build/libs'
      artifact: 'drop'
